### ISSUE TITLE
危険度の基準

### ISSUE THREAD

**Issue by HiroAsa** [codeformatsudo/matsumamo#8]
危険度の数値について基準を明確にする必要があるのでは

**Comment by egurin** [comment]
ごもっともです。今は、私がなんとなく割り振ってます。

**Comment by egurin** [comment]
以下の基準にしました。今後微調整したほうがいいかと思います。
暴行	700
痴漢	800
露出	500
つきまとい	400
声かけ	300
盗撮	200
